<?php require dirname(__DIR__).'/bootstrap.php'; require_once dirname(__DIR__, 2).'/cache-control.php'; $form=require dirname(__DIR__).'/config/form_fields.php'; $form['title']=(string)app_setting('form_title',$form['title']); ?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($form['title'])?></title>
<?php render_open_graph((string) $form['title'], (string) ($form['description'] ?? '')); ?>
<link rel="stylesheet" href="assets/css/app.css?v=20260803-4"></head><body>
<header><a class="brand" href="../../index.php" aria-label="Ir al inicio de Vásquez Kennedy"><img src="../../recursos-multimedia/logos/logo-vasquez-kennedy-header.webp" alt="Vásquez Kennedy" width="120" height="52"></a></header><main><section class="hero"><p class="eyebrow">PANEL INTERNACIONAL</p><h1><?=htmlspecialchars($form['title'])?></h1><p>Completa tus datos para reservar tu cupo. La fecha y hora ya están definidas.</p><div class="progress"><i id="bar"></i></div></section>
<form id="registrationForm"><input type="hidden" name="csrf" value="<?=csrf()?>"><div class="grid">
<?php foreach($form['fields'] as $f): ?><div class="field <?=$f['name']==='data_consent'?'wide consent':''?>"><label><?=htmlspecialchars($f['label'])?><?=$f['required']?' <em>*</em>':''?></label><?php if($f['type']==='radio'): ?><div class="choices"><?php foreach($f['options'] as $o): ?><label><input type="radio" name="<?=$f['name']?>" value="<?=htmlspecialchars($o)?>" <?=$f['name']==='data_consent'&&$o==='Sí'?'required':''?>> <?=htmlspecialchars($o)?></label><?php endforeach?></div><?php else: ?><input type="<?=$f['type']?>" name="<?=$f['name']?>" <?=$f['required']?'required':''?> autocomplete="<?=$f['type']==='email'?'email':'on'?>"><?php endif?><small class="error"></small></div><?php endforeach?>
<div class="field wide fixed-event"><p class="eyebrow">FECHA DEL EVENTO</p><strong>Jueves 13 de agosto de 2026 · 5:00 p. m.</strong><span>Zona horaria: America/Bogota (Colombia)</span></div>
<input type="hidden" name="timezone" value="America/Bogota"><input type="hidden" name="selected_date" value="2026-08-13"><input type="hidden" name="selected_start_utc" id="startUtc" value="2026-08-13T22:00:00Z" required></div><button type="submit" id="submit">Inscribirme y agendar</button><p id="notice" role="status"></p></form></main><div id="loading" hidden><div class="spinner"></div><p>Verificando tu inscripción y reservando tu cupo…</p></div><script src="assets/js/app.js?v=20260803-2"></script></body></html>
