<?php
require dirname(__DIR__,2).'/bootstrap.php';
use App\Services\{CalendlyService,GoogleSheetsService,MailService};
if($_SERVER['REQUEST_METHOD']!=='POST')json_response(['message'=>'Método no permitido'],405);
if(!hash_equals(csrf(),$_POST['csrf']??''))json_response(['message'=>'Sesión expirada. Recarga la página.'],419);
$ip=hash('sha256',($_SERVER['REMOTE_ADDR']??'').envv('APP_KEY')); $_SESSION['attempts']=array_values(array_filter($_SESSION['attempts']??[],fn($t)=>$t>time()-60)); if(count($_SESSION['attempts'])>=5)json_response(['message'=>'Demasiados intentos. Espera un minuto.'],429); $_SESSION['attempts'][]=time();
$required=['first_name','last_name','email','phone','country','profession','position','company','timezone','selected_start_utc']; foreach($required as $k)if(trim($_POST[$k]??'')==='')json_response(['message'=>'Falta completar: '.$k],422); if(!filter_var($_POST['email'],FILTER_VALIDATE_EMAIL))json_response(['message'=>'Correo inválido'],422); if(($_POST['data_consent']??'')!=='Sí')json_response(['message'=>'Debes autorizar el tratamiento de datos para continuar.'],422);
$tz=new DateTimeZone($_POST['timezone']); $utc=(new DateTimeImmutable($_POST['selected_start_utc']))->setTimezone(new DateTimeZone('UTC')); if($utc<new DateTimeImmutable('now',new DateTimeZone('UTC')))json_response(['message'=>'El horario ya pasó.'],422); $local=$utc->setTimezone($tz); $uuid=sprintf('%s-%s-4%s-%s%s-%s',bin2hex(random_bytes(4)),bin2hex(random_bytes(2)),substr(bin2hex(random_bytes(2)),1),dechex(random_int(8,11)),substr(bin2hex(random_bytes(2)),1),bin2hex(random_bytes(6))); $key=hash('sha256',strtolower($_POST['email']).'|'.envv('CALENDLY_EVENT_TYPE_URI').'|'.$utc->format('c').'|'.$uuid); $answers=$_POST; unset($answers['csrf']);
try{$pdo=db();$pdo->beginTransaction();$q=$pdo->prepare("INSERT INTO registrations(uuid,full_name,email,phone,timezone,selected_start_local,selected_start_utc,status,form_response_json,idempotency_key) VALUES(?,?,?,?,?,?,?,'processing',?,?)");$q->execute([$uuid,trim($_POST['first_name'].' '.$_POST['last_name']),strtolower($_POST['email']),$_POST['phone'],$_POST['timezone'],$local->format('Y-m-d H:i:s'),$utc->format('Y-m-d H:i:s'),json_encode($answers,JSON_UNESCAPED_UNICODE),$key]);$id=(int)$pdo->lastInsertId();$pdo->commit();
 try{$cal=new CalendlyService; $nowUtc=new DateTimeImmutable('now',new DateTimeZone('UTC')); $availabilityFrom=$nowUtc->modify('+1 minute'); $availabilityTo=$utc->setTime(23,59,59); if($availabilityTo<=$availabilityFrom)$availabilityTo=$availabilityFrom->modify('+1 day'); $check=$cal->availability($availabilityFrom->format('Y-m-d\TH:i:s\Z'),$availabilityTo->format('Y-m-d\TH:i:s\Z')); $available=array_filter($check['collection']??[],fn($s)=>isset($s['start_time'])&&strtotime((string)$s['start_time'])===$utc->getTimestamp()); if(!$available)throw new RuntimeException('Calendly no ofreció el horario configurado.'); $result=$cal->createInvitee(trim($_POST['first_name'].' '.$_POST['last_name']),$_POST['email'],$_POST['timezone'],$utc->format('Y-m-d\TH:i:s\Z')); $res=$result['resource']??$result; $eventUri=$res['event']??'';$inviteeUri=$res['uri']??'';$eventUuid=basename($eventUri);$inviteeUuid=basename($inviteeUri);$cancel=$res['cancel_url']??'';$re=$res['reschedule_url']??'';$u=$pdo->prepare("UPDATE registrations SET status='scheduled',calendly_event_uri=?,calendly_event_uuid=?,calendly_invitee_uri=?,calendly_invitee_uuid=?,cancel_url=?,reschedule_url=?,calendly_response_json=?,error_message=NULL WHERE id=?");$u->execute([$eventUri,$eventUuid,$inviteeUri,$inviteeUuid,$cancel,$re,json_encode($result),$id]);}catch(Throwable $calendlyError){$pdo->prepare("UPDATE registrations SET status='pending',error_message=? WHERE id=?")->execute([$calendlyError->getMessage(),$id]);$pdo->prepare("INSERT INTO integration_logs(registration_id,service,action,success,error_message) VALUES(?,'calendly','create_invitee',0,?)")->execute([$id,$calendlyError->getMessage()]);} $row=$pdo->query('SELECT * FROM registrations WHERE id='.$id)->fetch();$row['answers']=$answers;
 try{(new GoogleSheetsService)->append($row);$pdo->prepare('UPDATE registrations SET sheets_synced_at=NOW() WHERE id=?')->execute([$id]);}catch(Throwable $e){$pdo->prepare("INSERT INTO integration_logs(registration_id,service,action,success,error_message) VALUES(?,'google_sheets','append',0,?)")->execute([$id,$e->getMessage()]);}
 try{(new MailService)->send($row);$pdo->prepare('UPDATE registrations SET email_sent_at=NOW() WHERE id=?')->execute([$id]);}catch(Throwable $e){$pdo->prepare("INSERT INTO integration_logs(registration_id,service,action,success,error_message) VALUES(?,'mail','send',0,?)")->execute([$id,$e->getMessage()]);} json_response(['ok'=>true,'uuid'=>$uuid]);
}catch(Throwable $e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();if(isset($id))$pdo->prepare("UPDATE registrations SET status='failed',error_message=? WHERE id=?")->execute([$e->getMessage(),$id]);json_response(['message'=>$e->getMessage()],$e->getCode()===409?409:500);}
