<?php
namespace App\Services;
use RuntimeException;
class CalendlyService {
 private string $token; private string $base='https://api.calendly.com';
 public function __construct(){ $this->token=(string)envv('CALENDLY_ACCESS_TOKEN',''); if(!$this->token) throw new RuntimeException('CALENDLY_ACCESS_TOKEN no está configurado.'); }
 public function request(string $method,string $path,array $query=[],?array $body=null): array { $url=str_starts_with($path,'http')?$path:$this->base.$path; if($query)$url.='?'.http_build_query($query); $ch=curl_init($url); curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$this->token,'Content-Type: application/json'],CURLOPT_TIMEOUT=>25]); if($body!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($body)); $raw=curl_exec($ch); $code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE); $error=curl_error($ch); curl_close($ch); $data=json_decode((string)$raw,true)?:[]; if($error||$code<200||$code>=300) throw new RuntimeException($data['message']??$error?:'Calendly HTTP '.$code,$code); return $data; }
 private function eventTypeUri(): string { $uri=(string)(event_config()['calendly_event_type_uri']??''); if(!$uri)throw new RuntimeException('Configura el enlace del evento de Calendly desde el administrador.'); return $uri; }
 private function configuredEventTypeUri(): string { $uri=(string)envv('CALENDLY_EVENT_TYPE_URI',''); return preg_match('#^https://api\.calendly\.com/event_types/[a-z0-9-]+/?$#i',$uri)?rtrim($uri,'/'):''; }
 public function resolveEventTypeUri(string $link): string { $link=trim($link); if(preg_match('#^https://api\.calendly\.com/event_types/[a-z0-9-]+/?$#i',$link))return rtrim($link,'/'); if($configured=$this->configuredEventTypeUri())return $configured; $scope=[];$user=(string)envv('CALENDLY_USER_URI','');$organization=(string)envv('CALENDLY_ORGANIZATION_URI','');if(!$user&&!$organization){$me=$this->request('GET','/users/me');$user=(string)($me['resource']['uri']??'');}if($user)$scope['user']=$user;elseif($organization)$scope['organization']=$organization;else throw new RuntimeException('Calendly no devolvió el usuario asociado al token. Configura CALENDLY_EVENT_TYPE_URI con la URI API del evento.');$scope['count']=100;$data=$this->request('GET','/event_types',$scope);$wanted=rtrim(strtok($link,'?'),'/');foreach($data['collection']??[] as $event){$scheduling=rtrim(strtok((string)($event['scheduling_url']??''),'?'),'/');if($scheduling===$wanted)return (string)$event['uri'];}throw new RuntimeException('El enlace no corresponde a un tipo de evento accesible con este token de Calendly.'); }
 public function availability(string $from,string $to): array { $uri=$this->eventTypeUri(); return $this->request('GET','/event_type_available_times',['event_type'=>$uri,'start_time'=>$from,'end_time'=>$to]); }
 public function createInvitee(string $name,string $email,string $timezone,string $start): array { return $this->request('POST','/invitees',[],['event_type'=>$this->eventTypeUri(),'start_time'=>$start,'invitee'=>['name'=>$name,'email'=>$email,'timezone'=>$timezone]]); }
}
